### ISSUE TITLE
Error post time

### ISSUE THREAD

**Issue by Seele0oO** [techbarrack/terminal-hugo-theme#3]
![image](https://github.com/techbarrack/terminal-hugo-theme/assets/48525679/e6e2b0cb-edf5-4978-9b1b-e25ee2531405)

all of the post time is "⏰ 23:33:10+05:30"

**Comment by Seele0oO** [comment]
https://github.com/techbarrack/terminal-hugo-theme/pull/4
here is a pr.

**Comment by nayanseth** [comment]
Thanks
